LOG:  database system was interrupted; last known up at 2021-01-27 13:31:37 JST
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 4/9A3CAAD0: wanted 24, got 0
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  database "fx_db" does not exist
ERROR:  canceling statement due to user request
LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2021-01-27 20:07:14 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  canceling statement due to user request
LOG:  received fast shutdown request
LOG:  aborting any active transactions
FATAL:  terminating connection due to administrator command
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2021-01-27 20:08:17 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  no schema has been selected to create in at character 14
STATEMENT:  CREATE TABLE "django_migrations" ("id" serial NOT NULL PRIMARY KEY, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" timestamp with time zone NOT NULL)
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.
	
LOG:  server process (PID 27836) was terminated by exception 0xC000013A
HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
LOG:  statistics collector process (PID 21732) was terminated by exception 0xC000013A
HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2021-01-27 23:43:20 JST
